class ClinicModel {
  String id,
      docid,
      clinic,
      phoneno,
      address,
      lattitude,
      longitude,
      appoitmentduration,
      maxnotobook,
      appoitmentfee,
      sundaystatus,
      sundaystarttiming,
      sundayofftiming,
      mondaystatus,
      mondaystarttiming,
      mondayofftiming,
      tuesdaystatus,
      tuesdaystarttiming,
      tuesdayofftiming,
      wednesdaystatus,
      wednesdaystarttiming,
      wednesdayofftiming,
      thursdaystatus,
      thursdaystarttiming,
      thursdayofftiming,
      fridaystatus,
      fridaystarttiming,
      fridayofftiming,
      saturdaystatus,
      saturdaystarttiming,
      saturdayofftiming;
  ClinicModel(
      {this.id,
      this.docid,
      this.address,
      this.appoitmentduration,
      this.appoitmentfee,
      this.clinic,
      this.phoneno,
      this.fridayofftiming,
      this.fridaystarttiming,
      this.fridaystatus,
      this.lattitude,
      this.longitude,
      this.maxnotobook,
      this.mondayofftiming,
      this.mondaystarttiming,
      this.mondaystatus,
      this.saturdayofftiming,
      this.saturdaystarttiming,
      this.saturdaystatus,
      this.sundayofftiming,
      this.sundaystarttiming,
      this.sundaystatus,
      this.thursdayofftiming,
      this.thursdaystarttiming,
      this.thursdaystatus,
      this.tuesdayofftiming,
      this.tuesdaystarttiming,
      this.tuesdaystatus,
      this.wednesdayofftiming,
      this.wednesdaystarttiming,
      this.wednesdaystatus});
  factory ClinicModel.fromjson(Map<String, dynamic> json) {
    return ClinicModel(
      id: json['id'],
      docid: json['docid'],
      clinic: json['clinic'],
      address: json['address'],
      appoitmentduration: json['appoitmentduration'],
      appoitmentfee: json['appoitmentfee'],
      fridayofftiming: json['appoitmentfee'],
      fridaystarttiming: json['fridaystarttiming'],
      fridaystatus: json['fridaystatus'],
      lattitude: json['lattitude'],
      longitude: json['longitude'],
      maxnotobook: json['maxnotobook'],
      mondayofftiming: json['mondayofftiming'],
      mondaystarttiming: json['mondaystarttiming'],
      mondaystatus: json['mondaystatus'],
      phoneno: json['phoneno'],
      saturdayofftiming: json['saturdayofftiming'],
      saturdaystarttiming: json['saturdaystarttiming'],
      saturdaystatus: json['saturdaystatus'],
      sundayofftiming: json['sundayofftiming'],
      sundaystarttiming: json['sundaystarttiming'],
      sundaystatus: json['sundaystatus'],
      thursdayofftiming: json['thursdayofftiming'],
      thursdaystarttiming: json['thursdaystarttiming'],
      thursdaystatus: json['thursdaystatus'],
      tuesdayofftiming: json['tuesdayofftiming'],
      tuesdaystarttiming: json['tuesdaystarttiming'],
      tuesdaystatus: json['tuesdaystatus'],
      wednesdayofftiming: json['wednesdayofftiming'],
      wednesdaystarttiming: json['wednesdaystarttiming'],
      wednesdaystatus: json['wednesdaystatus'],
    );
  }
}
